/**
 * Precompute the demo drafts' lints from the real parser, so iOS Safari (which
 * can't load the 145 MB model without an OOM tab-kill) can render the fully
 * marked-up manuscript statically. Run locally (`npm run gen:demo-lints`) — the
 * output JSON is committed and bundled into the client.
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { Linter, resolveConfig } from 'writinglint-core';
import { loadParser } from 'writinglint-parser-node';
import { recommended } from 'writinglint-rulepack-ai-style';
import { AI_PITCH, HUMAN_PITCH } from '../packages/web/src/client/examples.js';

const parser = await loadParser({ modelDir: resolve('models/xsmall') });
const linter = new Linter(parser);
const config = resolveConfig(recommended);

const dump: Record<string, string> = {};
for (const [key, text] of [['ai', AI_PITCH], ['human', HUMAN_PITCH]] as const) {
  const { lints } = await linter.lint(text, config);
  const slim = lints.map((l) => ({
    ruleId: l.ruleId,
    category: l.category,
    message: l.message,
    text: l.text,
    start: l.start,
    end: l.end,
    severity: l.severity,
  }));
  dump[key] = JSON.stringify(slim);
  console.error(`${key}: ${lints.length} lints`);
}
const file = `// AUTO-GENERATED by scripts/gen-demo-lints.ts — do not edit by hand.
// Precomputed lints for the demo drafts, so iOS Safari (which OOM-kills the 145 MB
// model) can render the marked-up manuscript statically. Regenerate: npm run gen:demo-lints
import type { Lint } from 'writinglint-core';

export const AI_LINTS = ${dump.ai} as unknown as Lint[];
export const HUMAN_LINTS = ${dump.human} as unknown as Lint[];
`;
writeFileSync('packages/web/src/client/precomputed-lints.ts', file);
console.error('wrote packages/web/src/client/precomputed-lints.ts');
